apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: using-build-and-deploy-
spec:
  pipelineRef:
    name: build-and-deploy
  workspaces:
  - name: build-workspace
    persistentVolumeClaim:
      claimName: shared-task-storage
  params:
  - name: repo-url
    value: http://192.168.1.221/edualex/wastest.git
  - name: branch-name
    value: master
  - name: repo-dockerfile
    value: Dockerfile
  - name: image-url
    value: image-registry.openshift-image-registry.svc:5000/myproject/defaultapplication:latest
